// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/jmoiron/sqlx"
	"main/cmd/repositories"
	"main/cmd/server"
	"main/cmd/services"
)

// Injectors from wire.go:

func NewRealUserRepository() *repository.SqlxUsersRepository {
	sqlxUsersRepository := ProvideRealUserRepository()
	return sqlxUsersRepository
}

func NewRealUsersService() *service.UsersService {
	usersService := ProvideRealUsersService()
	return usersService
}

func NewRealHandler() *server.Handler {
	handler := ProvideRealHander()
	return handler
}

// wire.go:

func ProvideRealUserRepository() *repository.SqlxUsersRepository {
	return &repository.SqlxUsersRepository{
		DB: &sqlx.DB{},
	}
}

func ProvideRealUsersService() *service.UsersService {
	return NewRealUsersService()
}

func ProvideRealHander() *server.Handler {
	return &server.Handler{
		UsersService: *NewRealUsersService(),
	}
}
